src/main/java/pap/mesus/model/domain/Doacao.java
package pap.mesus.model.domain;

import java.io.Serializable;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Repository;

import pap.mesus.model.domain.abstracts.CipherId;

@Entity
@Table(name = "DOACAO")
@Repository
@Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
public class Doacao extends CipherId implements Serializable {
	private static final long serialVersionUID = 1L;
	private static final String TABELA_DOACAO = "DOACAO";
	private static final String COLUNA_ID = "ID";
	private static final String COLUNA_GRAMAS = "GRAMAS";
	private static final String COLUNA_DATA = "DATA";
	private static final String DATE = "DATE";
	private static final String COLUNA_USUARIO = "USUARIO_ID";
	private static final String COLUNA_GRUPO_ALIMENTAR = "GRUPO_ALIMENTAR_ID";
	public static final String COLUNA_STATUS = "STATUS_ID";
	private static final String COLUNA_IDENTIFICADOR = "IDENTIFICADOR";

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(table = TABELA_DOACAO, name = COLUNA_ID)
	private Integer id;

	@Column(table = TABELA_DOACAO, name = COLUNA_GRAMAS, nullable = false)
	private Integer gramas;

	@Column(table = TABELA_DOACAO, name = COLUNA_IDENTIFICADOR, nullable = false, unique = true)
	private Long identificador;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(table = TABELA_DOACAO, name = COLUNA_DATA, nullable = false, columnDefinition = DATE)
	private Date data;

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, optional = false)
	@JoinColumn(name = COLUNA_USUARIO, nullable = false, insertable = true, updatable = true)
	private Usuario usuario;

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, optional = false)
	@JoinColumn(name = COLUNA_GRUPO_ALIMENTAR, nullable = false, insertable = true, updatable = true)
	private GrupoAlimentar grupoAlimentar;

	@OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL, optional = false)
	@JoinColumn(name = COLUNA_STATUS, nullable = false, insertable = true, updatable = true)
	private Status status;

	@Override
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGramas() {
		return gramas;
	}

	public void setGramas(Integer gramas) {
		this.gramas = gramas;
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Transient
	public String getDataFormatada() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		return sdf.format(getData());
	}

	@Transient
	public int getPrazoDias() {
		Calendar agora = Calendar.getInstance();
		Calendar e = Calendar.getInstance();
		e.setTime(getData());
		e.add(Calendar.DAY_OF_MONTH, getGrupoAlimentar().getValidade());
		int r = (int) ((e.getTimeInMillis() - agora.getTimeInMillis()) / (3600000 * 24));
		return r >= 0 ? r + 1 : 0;
	}

	@Transient
	public String getPesoKg() {
		Double p = (double) (getGramas() / 1000);
		Locale ptBr = new Locale("pt", "BR");
		NumberFormat nf = NumberFormat.getNumberInstance(ptBr);
		nf.setGroupingUsed(true);
		return nf.format(p);
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public GrupoAlimentar getGrupoAlimentar() {
		return grupoAlimentar;
	}

	public void setGrupoAlimentar(GrupoAlimentar grupoAlimentar) {
		this.grupoAlimentar = grupoAlimentar;
	}

	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Long getIdentificador() {
		return identificador;
	}

	public void setIdentificador(Long identificador) {
		this.identificador = identificador;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Doacao other = (Doacao) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/pap/mesus/controller/ContatoController.java
package pap.mesus.controller;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import pap.mesus.comunication.EnvioEmail;
import pap.mesus.model.domain.Usuario;

@Controller
public class ContatoController {
	private static final String IFRAME_CONTATO = "/area/contato";
	private static final String JSP_CONTATO = "contato";
	private static final String AJAX_FALE_CONOSCO = "/area/faleconosco";

	@Autowired
	EnvioEmail envioEmail;

	@RequestMapping(value = { IFRAME_CONTATO })
	public ModelAndView iframeListarDoacao(ModelMap modelMap, HttpSession httpSession) {
		return new ModelAndView(JSP_CONTATO);
	}

	@RequestMapping(value = AJAX_FALE_CONOSCO, method = RequestMethod.POST)
	@ResponseBody
	public String enviarContato(@RequestParam String assunto, @RequestParam String mensagem, HttpSession httpSession) {
		try {
			Usuario u = (Usuario) httpSession.getAttribute(PrincipalController.DADOS_USUARIO);
			String de = u.getEmail();
			envioEmail.contato(de, assunto, mensagem);
			return String.valueOf(true);
		} catch (Exception e) {
			e.printStackTrace();
			return String.valueOf(false);
		}

	}
}

src/main/webapp/WEB-INF/views/403.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%><%@ taglib
	prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page
	isELIgnored="false"%><%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %><%@ page contentType="text/html; charset=UTF-8"%><!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Nada de prato vazio!</title>
	<spring:url value="/resources/imagens/rotten-tomato.jpg" var="tomate" />
	<link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css' />
	<style>
	
	body {
		margin: 0;
		font-family: 'Ubuntu', sans-serif;
		position: absolute;
		width: 800px;
		top: 50px;
		margin-left: -400px;
		left: 50%;
	}
	img, div {
		float: left;
		
	}
	img {
		margin: 100px 20px;
		
	}
	h2 {
		width: 300px;
		text-align: justify;
	}
	h1 {
		font-size: 100px;
		color: #F00;
		text-shadow: -3px -3px 4px rgba(255, 0, 0, 1);
	}
	</style>
 </head>
   
 <body>
   <img alt="Erro!" src="${tomate}" />
   <div>
   	<h1>Ooops!</h1>
   	<div>Você não possui permissão para acessar esta página! Retornando à página principal em <span>10</span> segundo<span>s</span></div>
   </div>
 </body>
 </html>

src/main/webapp/WEB-INF/views/conta.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%><%@ taglib
	prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page
	isELIgnored="false"%><%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %><%@ page contentType="text/html; charset=UTF-8"%><!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Nada de prato vazio!</title>
	<spring:url value="/resources/css/style.css" var="coreCss" />
	<spring:url value="/resources/css/style_cadastro.css" var="cadastroCss" />
	<spring:url value="/resources/imagens/mesus.png" var="logotipo" />
	<spring:url value="/resources/imagens/fechar.png" var="fechar" />
	<spring:url value="/resources/js/jquery.min.js" var="jQuery" />
	<spring:url value="/resources/js/mask.js" var="mask" />
	<spring:url value="/resources/ps" var="perfectscrollbar" />
	<spring:url value="/resources/imagens/favicon" var="favicon" />
	
	
	<jsp:include page="favicons.jsp" />
	
	<link rel="stylesheet" href="${perfectscrollbar}/css/perfect-scrollbar.min.css" />
	<link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css' />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
	<link href="${coreCss}" rel="stylesheet" />
	<link href="${cadastroCss}" rel="stylesheet" />
  	<script src="${jQuery}"> </script>
  	<script src="${mask}"> </script>
  	<script src="${perfectscrollbar}/js/perfect-scrollbar.jquery.min.js"> </script>
  	<script>
  	$(document).ready(function(){
  		$('#cepUsuario').mask('00.000-000');
  		$('#botContinuar').click(function() {
  			$('#cadastroInicio').submit();
  		});
  		var erros = $('#erros');
  		if($('#grupoErros').children('div').length > 0){
  			erros.animate({
  				bottom: 0
  			}, 600);
  		}
  		$('#fecharErro').click(function() {
  			erros.animate({
  				bottom: '-1000px'
  			}, 600);
  		});
  		
  		
  	});
  	</script>
 </head>
   
 <body>
   <header>
   	<nav>
   		<div id="cabecalhoParteEsquerda">
   			<c:url var="index" value="/" />
				<a href="${index }" style="border: none;"><img src="${logotipo}"
					alt="Mesus" /></a>
   		</div>
   		<c:url var="irpainel" value="/area/principal" />
   		<div id="cabecalhoParteDireita">
   			<div><a href="sobre">Sobre</a></div>
   			<div><a href="pr">Perguntas &amp; Respostas</a></div>
   			<div><a href="${irpainel}">Entrar</a></div>
   		</div>
   	</nav>
   </header>
   <section>
	   <div id="faixaCentral">
	   		<div id="passos">
	   		<div class="numeroPasso numeroPassoPosicaoAtual">1</div>
	   		<div class="traco">____________________</div>
	   		<div class="numeroPasso">2</div>
	   		<div class="traco">____________________</div>
	   		<div class="numeroPasso">3</div>
	   	</div>
		<h1>Entre com seu e-mail e CEP para começar!</h1>
		<h2>Seja parte da luta contra a fome.</h2>
		
	</div>
	
   </section>
   <form:form method="POST" modelAttribute="primeiroPasso" action="email_cep" id="cadastroInicio">
			<div id="erros">
			<div style="text-align: right"><img id="fecharErro" src="${fechar}" alt="fechar" /></div>
				<div id="grupoErros">
					<form:errors path="email" element="div" />
					<form:errors path="CEP" element="div" />
				</div>
			</div>
			<div>
				<div class="rotulo">e-mail</div>
				<div>
					<form:input path="email" placeholder="E.g.  lorem@ipsum.com" id="emailUsuario" type="email" />
					
				</div>
			</div>
			<div>
				<div class="rotulo">CEP</div>
				<div>
					<form:input path="CEP" type="email" placeholder="E.g.   12.345-532" id="cepUsuario" />
					<div id="botContinuar" class="botao">Continuar</div>
				</div>
				
			</div>
			
	</form:form>
    
   
 </body>
 </html>

src/main/webapp/WEB-INF/views/contato.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%><%@taglib
	uri="http://www.springframework.org/tags/form" prefix="form"%><%@ taglib
	prefix="sec" uri="http://www.springframework.org/security/tags"%><%@ taglib
	prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page
	isELIgnored="false"%><%@ taglib
	uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%><%@ page
	contentType="text/html; charset=UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<spring:url value="/resources/imagens/frente" var="frente" />
<spring:url value="/resources/css/style.css" var="coreCss" />
<spring:url value="/resources/css/style_painel.css" var="painelCss" />
<spring:url value="/resources/css/style_cadastro2.css"
	var="formatarForms" />
<spring:url value="/resources/imagens/mesus.png" var="logotipo" />
<spring:url value="/resources/imagens/fechar.png" var="fechar" />
<spring:url value="/resources/js/jquery.min.js" var="jQuery" />
<spring:url value="/resources/js/mask.js" var="mask" />
<spring:url value="/resources/ps" var="perfectscrollbar" />
<link href='https://fonts.googleapis.com/css?family=Ubuntu'
	rel='stylesheet' type='text/css' />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
	rel="stylesheet" />
<link rel="stylesheet"
	href="${perfectscrollbar}/css/perfect-scrollbar.min.css" />
<link href="${coreCss}" rel="stylesheet" />
<link href="${formatarForms}" rel="stylesheet" />
<link href="${painelCss}" rel="stylesheet" />
<style>
body, html {
	height: 500px;
}

textarea {
	height: 200px;
}

textarea, input {
	margin: 0 0 30px 30px;;
	font-family: 'Ubuntu', sans-serif;
	width: 380px !important;
}

#titulo {
	padding: 30px;
	font-family: 'Ubuntu', sans-serif;
	font-size: 16px;
	width: 400px;
	color: #E37C37;
	text-align: justify;
}

#botEnviar {
	width: 360px;
	border-radius: 5px;
	font-family: 'Ubuntu', sans-serif;
	color: #FFF;
	font-size: 20px;
	font-weight: 100;
	text-align: center;
	cursor: default;
	padding: 10px 20px 10px 20px;
	text-decoration: none;
	background: #373737;
	margin-left: 30px;
}

#feedb {
	background-color: #EEE;
	padding: 10px;
	box-shadow: 5px 5px 5px 0px rgba(50, 50, 50, 0.75);
	border-radius: 5px;
	position: absolute;
	display: none;
	font-size: 14px;
	left: 50%;
	margin-left: -100px;
	width: 200px;
	top: 40px;
}
#contateme {
	position: absolute;
	left: 50%;
	width: 500px;
	margin-left: -250px;
}
</style>
<script src="${jQuery}"> </script>
<script src="${perfectscrollbar}/js/perfect-scrollbar.jquery.min.js"> </script>
<script src="${mask}"> </script>
<script>


$(document).ready(function() {
	$('#botEnviar').click(function() {
		window.parent.$('#carregando').show();
		window.parent.$('#logotipo').hide();
		$('input, textarea').prop('disabled', true);
		$.ajax({
			type: 'POST',
			url: 'faleconosco',
			data: { 
				assunto: $('#assunto').val(), 
				mensagem: $('#mensagem').val()
			},
			success: function(retorno) {
				window.parent.$('#carregando').hide();
				window.parent.$('#logotipo').show();
				$('input, textarea').prop('disabled', false);
				var ack;
				if(retorno == 'true') {
					$('input, textarea').val('');
					ack = '<span style="color: #070">Mensagem enviada com sucesso!</span>';
				} else {
					ack = '<span style="color: #700">Falha no envio! Tente novamente em instantes...</span>';
				}
				$('#feedb').html(ack);
				$('#feedb').fadeIn(function() {
					setTimeout(function() {
						$('#feedb').fadeOut();
					}, 4000);
				});
			}
		});
	});
	window.parent.$('#carregando').hide();
	window.parent.$('#logotipo').show();
});
</script>
</head>
<body>
	<div id="contateme">
		<div id="feedb"></div>
		<div id="titulo">Teve dificuldades em algum processo? Algum problema com alguma doação?
		Algum dado errado? Ou quer deixar algum elogio e sugestões? Fale conosco! 
		Iremos responder pelo e-mail cadastrado na sua conta!</div>
		<div><input maxlength="30" id="assunto" type="text" placeholder="Assunto:"></div>
		<div><textarea id="mensagem" placeholder="Digite aqui o que deseja falar..."></textarea></div>
		<div id="botEnviar">Enviar</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/cron.jsp
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%><%@ taglib
	prefix="sec" uri="http://www.springframework.org/security/tags"%><%@ taglib
	prefix="spring" uri="http://www.springframework.org/tags"%><%@ taglib
	prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page
	isELIgnored="false"%><%@ taglib
	uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%><%@ page
	contentType="text/html; charset=UTF-8"%><!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
</head>
<body>
crontab ok
</body>
</html>

src/main/webapp/WEB-INF/views/error.jsp
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%><%@ taglib
	prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page
	isELIgnored="false"%><%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %><%@ page contentType="text/html; charset=UTF-8"%><!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>Nada de prato vazio!</title>
	<spring:url value="/resources/imagens/rotten-tomato.jpg" var="tomate" />
	<link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css' />
	<style>
	
	body {
		margin: 0;
		font-family: 'Ubuntu', sans-serif;
		position: absolute;
		width: 800px;
		top: 50px;
		margin-left: -400px;
		left: 50%;
	}
	img, div {
		float: left;
		
	}
	img {
		margin: 100px 20px;
		
	}
	h2 {
		width: 300px;
		text-align: justify;
	}
	h1 {
		font-size: 100px;
		color: #F00;
		text-shadow: -3px -3px 4px rgba(255, 0, 0, 1);
	}
	</style>
 </head>
   
 <body>
   <img alt="Erro!" src="${tomate}" />
   <div>
   	<h1>Ooops!</h1>
   	<h2>Deu erro! Pedimos desculpas pelo desperdício... de tempo! Sua frustração foi registrada e trabalharemos o mais rápido possível para sanar!</h2>
   </div>
 </body>
 </html>

src/main/webapp/WEB-INF/views/favicons.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ page contentType="text/html; charset=UTF-8"%>

<spring:url value="/resources/imagens/favicon" var="favicon" />

<link rel="apple-touch-icon" sizes="57x57" href="${favicon}/apple-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="60x60" href="${favicon}/apple-icon-60x60.png" />
<link rel="apple-touch-icon" sizes="72x72" href="${favicon}/apple-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="76x76" href="${favicon}/apple-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="114x114" href="${favicon}/apple-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="120x120" href="${favicon}/apple-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="144x144" href="${favicon}/apple-icon-144x144.png" />
<link rel="apple-touch-icon" sizes="152x152" href="${favicon}/apple-icon-152x152.png" />
<link rel="apple-touch-icon" sizes="180x180" href="${favicon}/apple-icon-180x180.png" />
<link rel="icon" type="image/png" sizes="192x192"  href="${favicon}/android-icon-192x192.png" />
<link rel="icon" type="image/png" sizes="32x32" href="${favicon}/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="96x96" href="${favicon}/favicon-96x96.png" />
<link rel="icon" type="image/png" sizes="16x16" href="${favicon}/favicon-16x16.png" />
<link rel="manifest" href="${favicon}/manifest.json" />
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="${favicon}/ms-icon-144x144.png" />
<meta name="theme-color" content="#FFFFFF" />

src/main/webapp/WEB-INF/views/listaDoacao.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%><%@taglib
	uri="http://www.springframework.org/tags/form" prefix="form"%><%@ taglib
	prefix="sec" uri="http://www.springframework.org/security/tags"%><%@ taglib
	prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ page
	isELIgnored="false"%><%@ taglib
	uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%><%@ page
	contentType="text/html; charset=UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<spring:url value="/resources/imagens/frente" var="frente" />
<spring:url value="/resources/css/style.css" var="coreCss" />
<spring:url value="/resources/css/style_painel.css" var="painelCss" />
<spring:url value="/resources/css/style_cadastro2.css"
	var="formatarForms" />
<spring:url value="/resources/imagens/mesus.png" var="logotipo" />
<spring:url value="/resources/imagens/fechar.png" var="fechar" />
<spring:url value="/resources/js/jquery.min.js" var="jQuery" />
<spring:url value="/resources/js/mask.js" var="mask" />
<spring:url value="/resources/ps" var="perfectscrollbar" />
<link href='https://fonts.googleapis.com/css?family=Ubuntu'
	rel='stylesheet' type='text/css' />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
	rel="stylesheet" />
<link rel="stylesheet"
	href="${perfectscrollbar}/css/perfect-scrollbar.min.css" />
<link href="${coreCss}" rel="stylesheet" />
<link href="${formatarForms}" rel="stylesheet" />
<link href="${painelCss}" rel="stylesheet" />
<style>
body, html {
	height: 500px;
}

td i {
	font-size: 14px !important;
	cursor: default;
	color: #F70 !important;
	transition: all 0.7s ease;
}

table {
	border-collapse: collapse;
	margin-left: auto;
	margin-right: auto;
}

td i:hover {
	color: #0F0 !important;
}

th {
	background-color: #FA0;
	color: #FFF;
}

tr:first-child, tr:nth-child(even) {
	box-shadow: 0px 0px 10px 0px rgba(50, 50, 50, 0.75);
}

tr:nth-child(even) {
	background-color: #FDD;
}

th, td {
	padding: 10px;
	font-size: 14px;
}

td {
	text-align: center;
}

</style>
<script src="${jQuery}"> </script>
<script src="${perfectscrollbar}/js/perfect-scrollbar.jquery.min.js"> </script>
<script src="${mask}"> </script>
<script>
	var id;
	$(document).ready(function() {
		window.parent.$('#carregando').hide();
		window.parent.$('#logotipo').show();
		$('[data-edit]').click(function() {
			window.location.href='doar?edit=true&idEncriptado='+$(this).data('edit');
		});
		$('[data-cancel]').click(function() {
			$('#cancela').fadeIn();
			id = $(this).data('cancel');
		});
		$('[data-refresh]').click(function() {
			$('#refresh').fadeIn();
			id = $(this).data('refresh');
		});
		$('#cancelaNao').click(function() {
			$('#cancela').fadeOut();
			id = null;
		});
		$('#cancelaSim').click(function() {
			$('#cancela').fadeOut();
			window.parent.$('#carregando').show();
			window.parent.$('#logotipo').hide();
			window.location.href='cancelar?idEncriptado=' + id;
		});
		
		$('#concluiNao').click(function() {
			$('#conclui').fadeOut();
			id = null;
		});
		$('#concluiSim').click(function() {
			$('#conclui').fadeOut();
			window.location.href='concluirReserva?n=' + id;
			window.parent.$('#carregando').show();
			window.parent.$('#logotipo').hide();
		});
	});
</script>
</head>

<body>
	<div id="cancela" class="popupDecisao">
		Tem certeza que deseja cancelar a doação?
		<div>
			<div id="cancelaSim" class="popupSim">Sim</div>
			<div id="cancelaNao" class="popupNao">Não</div>
		</div>
	</div>
	<div id="conclui" class="popupDecisao">
		O receptor buscou a doação?
		<div>
			<div id="concluiSim" class="popupSim">Sim</div>
			<div id="concluiNao" class="popupNao">Não</div>
		</div>
	</div>
	
	<table>
		<tr>
			<th>Identificador</th>
			<th>Grupo Alimentar</th>
			<th>Peso (kg)</th>
			<th>Status</th>
			<th>Validade</th>
			<th colspan="2">Ações</th>
		</tr>
		<c:forEach items="${listaDoacoes }" var="doacoes">
			<tr>
				<td>${doacoes.identificador }</td>
				<td>${doacoes.grupoAlimentar.nome }</td>
				<td>${doacoes.pesoKg }</td>
				<td>${doacoes.status.titulo }</td>
				
				<c:choose>
					<c:when test="${doacoes.status.bloqueio}">
						<td>-------</td>
					</c:when>
					<c:otherwise>
						<td>${doacoes.prazoDias } dia${doacoes.prazoDias > 1 ? "s" : "" }</td>
					</c:otherwise>
				</c:choose>
				<c:choose>
					<c:when test="${doacoes.status.rotulo eq 'TRANSPORTE'}">
						<td colspan="2"><i class="material-icons" data-edit="${doacoes.idEncriptado()}">check</i></td>
					</c:when>
					<c:when test="${doacoes.status.bloqueio}">
						<td colspan="2"></td>
					</c:when>
					<c:otherwise>
						<td><i class="material-icons" data-edit="${doacoes.idEncriptado()}">mode_edit</i></td>
						<td><i class="material-icons" data-cancel="${doacoes.idEncriptado()}">cancel</i></td>
					</c:otherwise>
				</c:choose>
			</tr>
		</c:forEach>
	</table>
</body>
</html>